alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: heads-up-db
  version: "17"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: heads-up
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: heads-up-app
region: nyc
services:
- dockerfile_path: /Dockerfile
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${heads-up-db.DATABASE_URL}
  github:
    branch: master
    repo: akatechis/heads-up
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: heads-up
  source_dir: /
